In [1]:
import numpy as np

In [2]:
2+3

5

In [48]:
nums=[1,2,'3.0',True]

In [49]:
nums=np.array(nums)
nums

array(['1', '2', '3.0', 'True'], dtype='<U21')

In [50]:
nums.ndim

1

In [51]:
nums.shape

(4,)

In [52]:
nums.dtype

dtype('<U21')

In [55]:
arr=np.zeros((2,3))

In [56]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [59]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [62]:
arr=np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [66]:
rand_arr=np.random.randint(1,15,4)
rand_arr

array([1, 5, 7, 2])

In [69]:
rand_arr=np.random.rand(2,3)
rand_arr

array([[0.95897987, 0.55017931, 0.99824582],
       [0.6176318 , 0.25093452, 0.21328304]])

In [75]:
rand_arr=np.random.randn(15000)
rand_arr

array([-0.68497201, -1.1587448 ,  0.70615199, ...,  0.92684517,
       -2.07404846, -1.52136276])

In [76]:
np.mean(rand_arr)

-0.0018574579464755738

In [89]:
arr=np.random.randint(1,100,50)
arr

array([76, 54, 42, 37, 83, 56, 95, 33, 13, 75, 97, 78, 75, 21,  6, 31, 90,
       60, 92, 76, 35, 64,  4, 19, 24, 86, 99, 52, 65, 60, 81, 13, 51, 80,
       84, 67, 20, 39, 31, 71, 23, 59,  2, 41, 90, 75,  6, 12, 40, 93])

In [90]:
arr.ndim

1

In [91]:
arr.shape

(50,)

In [92]:
arr.reshape(2,10).shape

ValueError: ignored

In [93]:
arr.reshape(2,10).ndim

ValueError: ignored

In [ ]:
arr.reshape(2,10)

In [94]:
arr.reshape(20)

ValueError: ignored

In [95]:
arr

array([76, 54, 42, 37, 83, 56, 95, 33, 13, 75, 97, 78, 75, 21,  6, 31, 90,
       60, 92, 76, 35, 64,  4, 19, 24, 86, 99, 52, 65, 60, 81, 13, 51, 80,
       84, 67, 20, 39, 31, 71, 23, 59,  2, 41, 90, 75,  6, 12, 40, 93])

In [101]:
arr=arr.reshape(2,5,5)

In [102]:
arr

array([[[76, 54, 42, 37, 83],
        [56, 95, 33, 13, 75],
        [97, 78, 75, 21,  6],
        [31, 90, 60, 92, 76],
        [35, 64,  4, 19, 24]],

       [[86, 99, 52, 65, 60],
        [81, 13, 51, 80, 84],
        [67, 20, 39, 31, 71],
        [23, 59,  2, 41, 90],
        [75,  6, 12, 40, 93]]])

In [103]:
arr.ndim

3

In [114]:
arr=np.arange(1,111)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [126]:
arr=arr.reshape(5,-1)

In [127]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [137]:
np.random.seed(12)
arr=np.random.randint(1,101,15).reshape(3,5)
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [138]:
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [139]:
arr.size

15

In [140]:
arr=np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [142]:
arr[0]

5

In [143]:
arr[1]

10

In [144]:
arr[4]

25

In [145]:
arr[5]

IndexError: ignored

In [146]:
arr

array([ 5, 10, 15, 20, 25])

In [147]:
arr[-1]

25

In [148]:
arr[-4]

10

In [149]:
arr[5]

IndexError: ignored

In [150]:
arr[0:3]

array([ 5, 10, 15])

In [151]:
arr

array([ 5, 10, 15, 20, 25])

In [152]:
arr[0:2]

array([ 5, 10])

In [153]:
arr[-1]

25

In [154]:
arr[-4]

10

In [155]:
arr[:]

array([ 5, 10, 15, 20, 25])

In [156]:
arr[1:]

array([10, 15, 20, 25])

In [157]:
arr[0:3]

array([ 5, 10, 15])

In [158]:
arr[:2]

array([ 5, 10])

In [159]:
arr

array([ 5, 10, 15, 20, 25])

In [160]:
arr[-3:]

array([15, 20, 25])

In [161]:
arr[:]

array([ 5, 10, 15, 20, 25])

In [162]:
arr[1:4]

array([10, 15, 20])

In [164]:
arr[1:4:1]

array([10, 15, 20])

In [165]:
arr[1:4:2]

array([10, 20])

In [166]:
arr[::-1]

array([25, 20, 15, 10,  5])

In [167]:
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [168]:
matrix[0][1]

10

In [169]:
matrix[1][1]

25

In [171]:
matrix[[0,1]]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [172]:
matrix[0,1]

10

In [173]:
matrix[2,2]

45

In [174]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [179]:
matrix[:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [180]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [187]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [188]:
np.random.seed(123)
matrix2=np.random.randint(1,101,25).reshape(5,5)

In [189]:
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [190]:
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [194]:
matrix2[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

In [214]:
 arr=np.array([5,10,15,20,25,30])

In [215]:
sliced_arr=arr[2:5].copy()

In [216]:
sliced_arr

array([15, 20, 25])

In [217]:
arr[:2]=0

In [218]:
arr

array([ 0,  0, 15, 20, 25, 30])

In [219]:
sliced_arr

array([15, 20, 25])

In [220]:
arr

array([ 0,  0, 15, 20, 25, 30])

In [221]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [223]:
mask=arr>5
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [225]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [226]:
arr[arr<4]

array([1, 2, 3])

In [230]:
arr[arr%2==0]=0
# equal even to 0

In [231]:
arr[arr==5]

array([5])

In [232]:
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [240]:
arr=np.array([1,2,3,4]).reshape(2,2)

In [241]:
arr

array([[1, 2],
       [3, 4]])

In [242]:
arr*2

array([[2, 4],
       [6, 8]])

In [243]:
arr+5

array([[6, 7],
       [8, 9]])

In [244]:
arr**2

array([[ 1,  4],
       [ 9, 16]])

In [245]:
arr

array([[1, 2],
       [3, 4]])

In [246]:
arr**4

array([[  1,  16],
       [ 81, 256]])

In [247]:
arr

array([[1, 2],
       [3, 4]])

In [248]:
arr/1

array([[1., 2.],
       [3., 4.]])

In [249]:
1/0

ZeroDivisionError: ignored

In [250]:
arr/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

In [251]:
arr/1

array([[1., 2.],
       [3., 4.]])

In [262]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [263]:
arr1+arr2

array([ 6,  8, 10, 12])

In [264]:
arr1*arr2

array([ 5, 12, 21, 32])

In [265]:
arr1


array([1, 2, 3, 4])

In [266]:
arr2

array([5, 6, 7, 8])

In [267]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [269]:
arr1**arr2  
# power of arr2 from arr1

array([    1,    64,  2187, 65536])

In [271]:
arr1**arr1

array([  1,   4,  27, 256])

In [272]:
arr1

array([1, 2, 3, 4])

In [275]:
arr3=np.array([9,10,11,12])

In [276]:
arr1/arr2*arr3

array([1.8       , 3.33333333, 4.71428571, 6.        ])

In [287]:
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,3)

In [288]:
matrix2=np.random.randint(5,15,9).reshape(3,3)

In [289]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [290]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [291]:
matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [294]:
matrix1*matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [295]:
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

In [296]:
arr=np.array([2,80,1,97,5])


In [297]:
min(arr)

1

In [298]:
arr.min() 

1

In [299]:
arr.max()

97

In [300]:
arr.sum()

185

In [301]:
sum(arr)

185

In [302]:
np.argmin(arr)

2

In [303]:
np.argmax(arr)

3

In [304]:
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [305]:
arr

array([ 2, 80,  1, 97,  5])

In [306]:
np.exp(arr)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [308]:
2.71828
# 
2.71828**80

5.5403242392390125e+34

In [309]:
np.sign(arr)

array([1, 1, 1, 1, 1])

In [310]:
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [311]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [312]:
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [313]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [318]:
arr2=np.array([1,2,3,0],dtype=bool)

In [319]:
arr2

array([ True,  True,  True, False])

In [320]:
arr2=np.array([1,0,1,1],dtype=bool)
arr2

array([ True, False,  True,  True])

In [321]:
for i in arr2:
  print(i)

True
False
True
True


In [324]:
np.random.seed(123)
matrix=np.random.randint(1,11,9).reshape(3,3)

In [325]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [326]:
matrix.sum()

39

In [329]:
np.min(matrix)

1

In [331]:
np.max(matrix)

10

In [337]:
# row=1,column=0

matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [341]:
np.min(matrix,axis=1)

array([3, 2, 1])

In [342]:
np.min(matrix,axis=0)

array([2, 2, 1])

In [343]:
np.sum(matrix,axis=1)

array([13, 16, 10])

In [344]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39])

In [345]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [346]:
np.cumsum(matrix,axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]])

In [347]:
np.cumsum(matrix,axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]])

In [348]:
np.prod(matrix,axis=1)

array([63, 80, 14])

In [349]:
np.prod(matrix,axis=0)

array([42, 24, 70])

In [352]:
np.random.seed(123)
rand_arr=np.random.randint(1,15,15)

In [353]:
rand_arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [355]:
np.random.shuffle(rand_arr)

In [356]:
rand_arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [357]:
rand_arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [364]:
new_ar=np.unique(rand_arr)

In [365]:
new_ar

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [366]:
np.unique(rand_arr).size

10

In [367]:
np.unique(arr,return_index=True,return_counts=True)

(array([ 1,  2,  5, 80, 97]), array([2, 0, 4, 1, 3]), array([1, 1, 1, 1, 1]))

In [369]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
print(matrix1)
matrix2=np.random.randint(20,40,9).reshape(3,3)
print(matrix2)

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]
[[35 29 20]
 [34 20 35]
 [39 34 24]]


In [370]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [371]:
np.vstack((matrix1,matrix2)) 

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [373]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

In [375]:
np.hstack((ar1,ar2))

array([1, 2, 3, 4, 5, 6])

In [376]:
np.vstack((ar1,ar2))

array([[1, 2, 3],
       [4, 5, 6]])

In [377]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [378]:
arr1=np.arange(20,41)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [379]:
ar3=np.ones(10)*5
ar3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [384]:
ar4=np.random.randint(1,50,24).reshape(3,4,2)
ar4

array([[[45, 42],
        [49, 28],
        [23,  4],
        [ 4, 12]],

       [[22, 26],
        [40, 42],
        [35,  4],
        [12,  4]],

       [[31,  7],
        [10, 24],
        [15, 39],
        [20,  7]]])

In [387]:
ar5=np.random.rand(4,5)

In [388]:
ar5

array([[0.51312815, 0.66662455, 0.10590849, 0.13089495, 0.32198061],
       [0.66156434, 0.84650623, 0.55325734, 0.85445249, 0.38483781],
       [0.3167879 , 0.35426468, 0.17108183, 0.82911263, 0.33867085],
       [0.55237008, 0.57855147, 0.52153306, 0.00268806, 0.98834542]])

In [391]:
np.random.seed(123)
ar6=np.random.randint(1,50,20)
ar6

array([46,  3, 29, 35, 39, 18, 20, 43, 23, 34, 33, 48, 10, 33, 47, 33, 48,
       26, 20, 15])

In [392]:
ar6[ar6%2==-1]
ar6

array([46,  3, 29, 35, 39, 18, 20, 43, 23, 34, 33, 48, 10, 33, 47, 33, 48,
       26, 20, 15])

In [393]:
matrix = np.array([[5 , 10, 15, 20, 25],
                   [30, 35, 40, 45, 50],
                   [55, 60, 65, 70, 75],
                   [80, 85, 90, 95, 100]])


In [394]:
matrix

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [396]:
matrix[1:3,0:3]

array([[30, 35, 40],
       [55, 60, 65]])

In [397]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])


In [398]:
np.hstack((arr7,arr8))

array([1, 2, 3, 4, 5, 6])

In [399]:
matrix2 = np.random.randint(1,10,9).reshape(3,3)
matrix3 = np.random.randint(10,20,9).reshape(3,3)

In [402]:
display(matrix2,matrix3)

array([[5, 1, 1],
       [5, 2, 8],
       [4, 3, 5]])

array([[17, 12, 14],
       [18, 10, 17],
       [19, 13, 14]])

In [404]:
np.hstack((matrix2, matrix3))

array([[ 5,  1,  1, 17, 12, 14],
       [ 5,  2,  8, 18, 10, 17],
       [ 4,  3,  5, 19, 13, 14]])

In [405]:
np.vstack((matrix2, matrix3))

array([[ 5,  1,  1],
       [ 5,  2,  8],
       [ 4,  3,  5],
       [17, 12, 14],
       [18, 10, 17],
       [19, 13, 14]])

In [407]:
%timeit 2+3

100000000 loops, best of 5: 13.2 ns per loop


In [408]:
%timeit [i**2 for i in range(1,4)]

1000000 loops, best of 5: 1.14 µs per loop


In [414]:
%timeit l=[]
for i in range(1,10000):
  l.append(i**2)
l

10000000 loops, best of 5: 32.6 ns per loop


[1,
 4,
 9,
 1,
 4,
 9,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600

In [415]:
%timeit np.arange(1,10000)**2

The slowest run took 7.82 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 15.9 µs per loop
